apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-viewer
  labels:
    app: kafka-topic-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-viewer
  template:
    metadata:
      labels:
        app: kafka-topic-viewer
    spec:
      containers:
        - name: kafka-topic-viewer
          image: docker.redpanda.com/vectorized/console:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILEPATH
              value: "/tmp/config.yml"
            - name: CONSOLE_CONFIG_FILE
              value: '                kafka:
                  brokers: ["kafka-controller.default.svc.cluster.local:9092"]
                  schemaRegistry:
                    enabled: true
                    urls: ["http://kafka-controller.default.svc.cluster.local:8081"]
                redpanda:
                  adminApi:
                    enabled: true
                    urls: ["http://kafka-controller.default.svc.cluster.local:9644"]'
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-topic-viewer
spec:
  selector:
    app: kafka-topic-viewer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
